apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mango
  name: mango
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mango
  template:
    metadata:
      labels:
        app: mango
    spec:
      containers:
      - image: httpd:latest
        name: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mango-svc
spec:
  selector:
    app: mango
  ports:
  - protocol: TCP
    port: 80
  type: NodePort
