apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appleapp
  name: apple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apple-app
  template:
    metadata:
      labels:
        app: apple-app
    spec:
      containers:
      - image: httpd:latest
        name: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apple-svc
spec:
  selector:
    app: apple-app
  ports:
  - protocol: TCP
    port: 80
  type: NodePort
